import type { Book } from "../types";

export const demoBooks: Book[] = [
  {
    id: "b1",
    title: "Deep Learning with Python",
    author: "Francois Chollet",
    isbn: "9781617294433",
    description: "Neural networks and practical ML systems.",
    category: "AI",
    tags: ["ai", "ml", "python"],
    availableCopies: 6,
    totalCopies: 8,
    rating: 4.8,
    createdAt: new Date().toISOString(),
    branch: "Main",
    coverUrl: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "b2",
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann",
    isbn: "9781449373320",
    description: "A guide to scalable and reliable systems.",
    category: "Computer Science",
    tags: ["database", "architecture", "distributed"],
    availableCopies: 3,
    totalCopies: 10,
    rating: 4.9,
    createdAt: new Date().toISOString(),
    branch: "Main",
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "b3",
    title: "Modern Operating Systems",
    author: "A. S. Tanenbaum",
    isbn: "9780133591620",
    description: "Operating systems principles and implementation.",
    category: "Computer Science",
    tags: ["os", "systems"],
    availableCopies: 1,
    totalCopies: 7,
    rating: 4.6,
    createdAt: new Date().toISOString(),
    branch: "Engineering",
    coverUrl: "https://images.unsplash.com/photo-1491841573634-28140fc7ced7?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "b4",
    title: "Quantum Mechanics Essentials",
    author: "David J. Griffiths",
    isbn: "9781107189638",
    description: "Conceptual understanding of quantum systems.",
    category: "Physics",
    tags: ["physics", "quantum"],
    availableCopies: 2,
    totalCopies: 4,
    rating: 4.5,
    createdAt: new Date().toISOString(),
    branch: "Science",
    coverUrl: "https://images.unsplash.com/photo-1544717305-996b815c338c?auto=format&fit=crop&w=900&q=80",
  },
];
